name: "Build and Push Docker Images"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/**'

jobs:
  build-and-push:
    name: "Build and Push Docker Images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [php-cli]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Log In to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: fusionsbot
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./docker/${{ matrix.image }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest
          platforms: linux/amd64,linux/arm64
