name: "Continuous Integration"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version:
          - '8.1'
    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: none
        tools: composer

    - name: Restore Composer dependencies
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Run Composer normalized
      run: composer normalize --dry-run

    - name: Run Pint code sniffer
      run: composer fix-cs -- --test

    - name: Run unit tests
      run: vendor/bin/phpunit --stop-on-failure --stop-on-error
